<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pxoqxo.Quick\Pxoqxo.Quick.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Pxoqxo.Ext.Core">
      <HintPath>..\..\publish\Pxoqxo.Ext\em1.0\Pxoqxo.Ext.Core.dll</HintPath>
    </Reference>
    <Reference Include="Pxoqxo.UnitTest">
      <HintPath>..\..\publish\Pxoqxo.UnitTest\em1.0\Pxoqxo.UnitTest.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
